<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Bank;
class BankSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $banks = [
            'Academy Bank',
            'ACB Bank',
            'Abu Dhabi bank',
            'AgFirst Farm Credit Bank',
            'Agribank',
            'Alberta Treasury Bank ( ATB)',
            'American Express Bank',
            'American Savings Bank',
            'Arizona Financial Credit Union',
            'ANZ Bank',
            'Armed Forces Bank',
            'Austin Telco Federal Credit Union',
            'Bac A Bank',
            'Ban Viet Bank',
            'Bank of America (BOA)',
            'Bank of Botetourt',
            'Bank of Hawaii',
            'Bank of Montreal',
            'Bank of Nevada',
            'Bank of New Hampshire',
            'Bank of New York Mellon',
            'Bank of North Carolina',
            'Bank of the West',
            'Bank of Queensland',
            'Bank OZK',
            'BNP Paribas',
            'Bankwest',
            'BaoViet Bank',
            'Barclays Bank',
            'BECU',
            'BMO Bank North America',
            'BIDV',
            'Canadian Western Bank',
            'Chase Bank',
            'Capital One Bank',
            'Capitol Federal Savings Bank',
            'Central Bank',
            'Central Bank of Uruguay',
            'Comerica Bank',
            'Commonwealth Bank',
            'CIBC Bank',
            'Caisse d\'Epargne',
            'CIMB Bank',
            'CIT Bank',
            'Citibank USA',
            'Citizens Bank USA',
            'Citizens Equity First Credit Union',
            'City National Bank California',
            'City National Bank of Florida',
            'Credit One Bank',
            'Credit Suisse',
            'Deutsche Bank',
            'Dacotah Bank',
            'Dong A Bank',
            'Excite Credit Union',
            'Eximbank',
            'EAST WEST BANK',
            'Falcon International Bank',
            'First National Bank of Fort Smith',
            'Frost Bank',
            'FirstBank',
            'Fifth Third Bank',
            'First Commercial Bank',
            'Grow Financial Bank',
            'Golden Bank',
            'Green Dot Bank',
            'Halifax Bank',
            'Huntington Bank',
            'HD Bank',
            'HSBC Bank Australia',
            'HSBC Bank Canada',
            'HSBC Bank England',
            'HSBC Bank USA',
            'INTRUST Bank',
            'JPMorgan Chase Bank',
            'JP Morgan Australia Bank',
            'KBC Bank',
            'KeyPoint Credit Union',
            'KeyBank',
            'KNOXVILLE TVA EMPLOYEES CREDIT UNION',
            'Lake Michigan Credit Union',
            'Laurentian Bank of Canada',
            'LCL Bank',
            'LienVietPostBank',
            'LifeStore Bank',
            'Lloyds Bank',
            'Luther Burbank Savings',
            'MB Bank',
            'M&T Bank',
            'MSB Bank',
            'Mission Federal Credit Union',
            'Nam A Bank',
            'National Australia Bank',
            'National Bank of Canada',
            'National Savings Bank',
            'Nationwide Bank',
            'NatWest Bank',
            'Navy Federal Credit Union',
            'New York Commercial Bank',
            'OCB',
            'Old National Bank',
            'POSTEITALIANE',
            'PNC Bank',
            'Public Bank',
            'PVcomBank',
            'Regions Bank',
            'Reserve Bank of Australia',
            'Royal Bank of Canada (RBC)',
            'Sacombank',
            'SaigonBank',
            'Santander Bank',
            'SCB Bank',
            'SCE Federal Credit Union',
            'SchoolsFirst Federal Credit Union',
            'Scotiabank',
            'SeABank',
            'SHB Bank',
            'Shinhan Bank',
            'Silicon Valley Bank',
            'Simplii Financial Online Banking',
            'Société Générale',
            'Sparekassen Vendsyssel',
            'Standard Chartered Bank',
            'Sberbank',
            'Sterling Savings Bank',
            'SunTrust Banks',
            'Truist Bank',
            'TB Bank',
            'Techcombank',
            'Texas Capital Bank',
            'The Royal Bank of Scotland',
            'TD Bank',
            'TD Canada Trust Bank',
            'TP Bank',
            'UBS Bank',
            'UOB',
            'USAA Bank',
            'U.S. Bank',
            'Yorkshire Bank',
            'VietABank',
            'VietBank',
            'Vietcombank',
            'VietinBank',
            'VIB Bank',
            'Virgin Money',
            'VP Bank',
            'Wells Fargo Bank',
            'Westpac Bank',
            'Wilshire Bank',
            'Woori Bank',
            'US Bank',
            'Suimitomo Mitsui',
            '三井住友銀行',
            'ゆうちょ銀行',
            'BIDV',
            'vietinbank',
            'Vietcombank',
            'VPbank',
            'MBbank',
            'Techcombank',
            'ACB',
            'SHB',
            'STAR Financial Bank',
            'HDBank',
            'SCB',
            'Sacombank',
            'Star bank',
            'TPBank',
            'VIB',
            'MSB',
            'SeABank',
            'OCB',
            'Bac A Bank',
            'ABBANK',
            'Đông Á Bank',
            'vietbank',
            'Kienlongbank',
            'Shinhan Bank',
            'Woori Bank',
            '中國信託銀行（CTBC Bank )',
            'Sparkasse Schwarzwald Baar',
            'crédit mutuel',
            'UFJ',
            'Mitsui Sumitomo',
            'Mizuho',
            'Risona',
            'Berliner Sparkassex ',
            'Česká spořitelna',
            'Sparkasse Wittgenstein',
            'ČSOB',
            'Ngân hàng Quốc Dân NCB',
            'yokoshin',
            '華南銀行',
            'DongA Bank',
            '三菱　UFJ 銀行',
            '하나은행',
            'DAEGU BANK',
            'Daegu Bank',
            'Commerzbank',
            'LPbank',
            'LA BANQUE POSTALE ',
            'ACH',
            'sparkasse',
            'NOVAV KBM',
            'NovaKBM',
            'Woodforest National Bank',
            'THE NISHI-NIPPON CITY BANK',
            'KNOXVILLE TVA EMPLOYEES CREDIT UNION'
        ];

        foreach ($banks as $bank) {
            Bank::create(['name' => $bank]);
        }
    }
}
